-- Generated by Oracle SQL Developer Data Modeler 18.4.0.339.1536
--   at:        2019-05-01 15:45:50 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE tbl_accesos (
    codigo_acceso    INTEGER NOT NULL,
    codigo_usuario   INTEGER NOT NULL,
    fecha_acceso     DATE
);

ALTER TABLE tbl_accesos ADD CONSTRAINT tbl_accesos_pk PRIMARY KEY ( codigo_acceso );

CREATE TABLE tbl_activar_notificaciones (
    codigo_activacion   INTEGER NOT NULL,
    nombre_activacion   VARCHAR2(20)
);

ALTER TABLE tbl_activar_notificaciones ADD CONSTRAINT tbl_activar_notificaciones_pk PRIMARY KEY ( codigo_activacion );

CREATE TABLE tbl_agregar_fotos_filtro (
    codigo_agregar_foto        INTEGER NOT NULL,
    codigo_filtro              INTEGER NOT NULL,
    codigo_usuario             INTEGER NOT NULL,
    descripcion_agregar_foto   VARCHAR2(50)
);

ALTER TABLE tbl_agregar_fotos_filtro ADD CONSTRAINT tbl_agregar_fotos_pk PRIMARY KEY ( codigo_agregar_foto );

CREATE TABLE tbl_autenticacion (
    codigo_tipo_autenticacion   INTEGER NOT NULL,
    codigo_usuario              INTEGER NOT NULL,
    fecha_activacion            DATE,
    app_o_num_cel               VARCHAR2(25)
);

CREATE TABLE tbl_bloqueo_usuarios (
    codigo_usuario             INTEGER NOT NULL,
    codigo_usuario_bloqueado   INTEGER NOT NULL,
    fecha_bloqueo              DATE NOT NULL
);

ALTER TABLE tbl_bloqueo_usuarios ADD CONSTRAINT tbl_bloqueo_usuarios_pk PRIMARY KEY ( codigo_usuario,
                                                                                      codigo_usuario_bloqueado );

CREATE TABLE tbl_canal_videos (
    codigo_canal             INTEGER NOT NULL,
    descripcion_activacion   VARCHAR2(25)
);

ALTER TABLE tbl_canal_videos ADD CONSTRAINT tbl_canal_videos_pk PRIMARY KEY ( codigo_canal );

CREATE TABLE tbl_categorias_publicacion (
    codigo_categoria             INTEGER NOT NULL,
    descripcion_tipo_categoria   VARCHAR2(100)
);

ALTER TABLE tbl_categorias_publicacion ADD CONSTRAINT tbl_categorias_publicacion_pk PRIMARY KEY ( codigo_categoria );

CREATE TABLE tbl_comentario (
    codigo_comentario            INTEGER NOT NULL,
    codigo_usuario               INTEGER NOT NULL,
    codigo_publicacion           INTEGER NOT NULL,
    codigo_comentario_superior   INTEGER,
    fecha_publicacion            DATE NOT NULL,
    comentario                   VARCHAR2(250),
    cantidad_likes               INTEGER
);

ALTER TABLE tbl_comentario ADD CONSTRAINT tbl_comentario_pk PRIMARY KEY ( codigo_comentario );

CREATE TABLE tbl_compartir_historias (
    codigo_compartir_historia        INTEGER NOT NULL,
    descripcion_compartir_historia   VARCHAR2(25)
);

ALTER TABLE tbl_compartir_historias ADD CONSTRAINT tbl_compartir_historias_pk PRIMARY KEY ( codigo_compartir_historia );

CREATE TABLE tbl_compartir_vista_previa (
    codigo_vista_previa        INTEGER NOT NULL,
    descripcion_vista_previa   VARCHAR2(10)
);

ALTER TABLE tbl_compartir_vista_previa ADD CONSTRAINT tbl_compartir_vista_previa_pk PRIMARY KEY ( codigo_vista_previa );

CREATE TABLE tbl_emojis (
    codigo_emoji   INTEGER NOT NULL,
    nombre_emoji   VARCHAR2(25),
    imagen_emoji   CLOB
);

ALTER TABLE tbl_emojis ADD CONSTRAINT tbl_emojis_pk PRIMARY KEY ( codigo_emoji );

CREATE TABLE tbl_estado_actividad (
    codigo_estado_act         INTEGER NOT NULL,
    nombre_estado_actividad   VARCHAR2(20)
);

ALTER TABLE tbl_estado_actividad ADD CONSTRAINT tbl_estado_actividad_pk PRIMARY KEY ( codigo_estado_act );

CREATE TABLE tbl_etiquetas (
    codigo_etiqueta             INTEGER NOT NULL,
    codigo_publicacion          INTEGER NOT NULL,
    codigo_usuario_etiquetado   INTEGER NOT NULL,
    fecha_etiqueta              DATE,
    coordenada_x_etiqueta       INTEGER,
    coordenada_y_etiqueta       INTEGER
);

ALTER TABLE tbl_etiquetas ADD CONSTRAINT tbl_etiquetas_pk PRIMARY KEY ( codigo_etiqueta,
                                                                        codigo_publicacion );

CREATE TABLE tbl_extension_publicacion (
    codigo_extension_publicacion   INTEGER NOT NULL,
    tipo_archivo                   VARCHAR2(20)
);

ALTER TABLE tbl_extension_publicacion ADD CONSTRAINT tbl_tipo_publicacion_pk PRIMARY KEY ( codigo_extension_publicacion );

CREATE TABLE tbl_favoritos (
    codigo_publicacion   INTEGER NOT NULL,
    cantidad_like        INTEGER
);

CREATE TABLE tbl_filtro_comentarios (
    codigo_palabra              INTEGER NOT NULL,
    descripcion_palabra_clave   VARCHAR2(25)
);

ALTER TABLE tbl_filtro_comentarios ADD CONSTRAINT tbl_filtro_comentarios_pk PRIMARY KEY ( codigo_palabra );

CREATE TABLE tbl_filtros (
    codigo_filtro    INTEGER NOT NULL,
    tipo_de_filtro   CLOB
);

ALTER TABLE tbl_filtros ADD CONSTRAINT tbl_filtros_pk PRIMARY KEY ( codigo_filtro );

CREATE TABLE tbl_genero (
    codigo_genero        INTEGER NOT NULL,
    descripcion_genero   VARCHAR2(20 CHAR),
    abreviatura_genero   CHAR(5 CHAR)
);

ALTER TABLE tbl_genero ADD CONSTRAINT tbl_genero_pk PRIMARY KEY ( codigo_genero );

CREATE TABLE tbl_historiales (
    codigo_historial        INTEGER NOT NULL,
    codigo_tipo_historial   INTEGER NOT NULL,
    codigo_usuario          INTEGER NOT NULL,
    fecha_modificacion      DATE,
    descripcion_cambio      VARCHAR2(100)
);

ALTER TABLE tbl_historiales ADD CONSTRAINT tbl_historiales_pk PRIMARY KEY ( codigo_historial );

CREATE TABLE tbl_igtv (
    codigo_video          INTEGER NOT NULL,
    codigo_canal          INTEGER NOT NULL,
    codigo_vista_previa   INTEGER NOT NULL,
    foto_portada          BLOB,
    video                 BLOB,
    titulo                VARCHAR2(50),
    descripcion           VARCHAR2(100),
    tamanio_video         INTEGER
);

ALTER TABLE tbl_igtv ADD CONSTRAINT tbl_igtv_pk PRIMARY KEY ( codigo_video );

CREATE TABLE tbl_inhabilitar_cuenta (
    codigo_inhabilitar_cuenta   INTEGER NOT NULL,
    descripcion_inhabilitar     VARCHAR2(50),
    fecha_inhabilitar           DATE,
    fecha_habilitar             DATE
);

ALTER TABLE tbl_inhabilitar_cuenta ADD CONSTRAINT tbl_inhabilitar_pk PRIMARY KEY ( codigo_inhabilitar_cuenta );

CREATE TABLE tbl_int_emoji (
    codigo_emoji        INTEGER NOT NULL,
    codigo_mensaje      INTEGER,
    codigo_comentario   INTEGER
);

CREATE TABLE tbl_likes (
    codigo_usuario       INTEGER NOT NULL,
    codigo_tipo_like     INTEGER NOT NULL,
    codigo_publicacion   INTEGER,
    codigo_comentario    INTEGER
);

CREATE TABLE tbl_lugares (
    codigo_lugar         INTEGER NOT NULL,
    codigo_lugar_padre   INTEGER,
    longitud             FLOAT,
    latitud              FLOAT,
    nombre_lugar         VARCHAR2(100)
);

ALTER TABLE tbl_lugares ADD CONSTRAINT tbl_lugares_pk PRIMARY KEY ( codigo_lugar );

CREATE TABLE tbl_mensajes (
    codigo_mensaje     INTEGER NOT NULL,
    codigo_emisor      INTEGER NOT NULL,
    codigo_receptor    INTEGER NOT NULL,
    codigo_tipo_like   INTEGER,
    fecha_envio        DATE NOT NULL,
    mensaje            VARCHAR2(250)
);

ALTER TABLE tbl_mensajes ADD CONSTRAINT tbl_mensajes_pk PRIMARY KEY ( codigo_mensaje );

CREATE TABLE tbl_palabras_filtro (
    codigo_palabra   INTEGER NOT NULL,
    codigo_usuario   INTEGER NOT NULL
);

ALTER TABLE tbl_palabras_filtro ADD CONSTRAINT tbl_palabras_filtro_pk PRIMARY KEY ( codigo_palabra,
                                                                                    codigo_usuario );

CREATE TABLE tbl_publicaciones (
    codigo_publicacion             INTEGER NOT NULL,
    codigo_tipo_publicacion        INTEGER NOT NULL,
    codigo_usuario                 INTEGER NOT NULL,
    codigo_extension_publicacion   INTEGER NOT NULL,
    codigo_categoria               INTEGER NOT NULL,
    nombre_archivo                 VARCHAR2(50),
    tamanio                        VARCHAR2(25),
    archivo                        CLOB,
    fecha_subida_archivo           DATE,
    cantidad_likes                 INTEGER
);

ALTER TABLE tbl_publicaciones ADD CONSTRAINT tbl_publicaciones_pk PRIMARY KEY ( codigo_publicacion );

CREATE TABLE tbl_publicaciones_guardadas (
    codigo_publicacion      INTEGER NOT NULL,
    codigo_usuario_guarda   INTEGER NOT NULL,
    fecha_guardada          DATE
);

ALTER TABLE tbl_publicaciones_guardadas ADD CONSTRAINT tbl_publicaciones_guardadas_pk PRIMARY KEY ( codigo_publicacion );

CREATE TABLE tbl_seguidos (
    codigo_usuario     INTEGER NOT NULL,
    codigo_seguidor    INTEGER NOT NULL,
    codigo_solicitud   INTEGER NOT NULL
);

ALTER TABLE tbl_seguidos ADD CONSTRAINT tbl_seguidos_pk PRIMARY KEY ( codigo_usuario,
                                                                      codigo_seguidor );

CREATE TABLE tbl_solicitud_seguidores (
    codigo_solicitud        INTEGER NOT NULL,
    descripcion_solicitud   VARCHAR2(50)
);

ALTER TABLE tbl_solicitud_seguidores ADD CONSTRAINT tbl_solicitud_seguidores_pk PRIMARY KEY ( codigo_solicitud );

CREATE TABLE tbl_susc_usu (
    codigo_usuario       INTEGER NOT NULL,
    codigo_suscripcion   INTEGER NOT NULL
);

CREATE TABLE tbl_suscripciones (
    codigo_suscripcion   INTEGER NOT NULL,
    nombre_suscripcion   VARCHAR2(100)
);

ALTER TABLE tbl_suscripciones ADD CONSTRAINT tbl_suscripciones_pk PRIMARY KEY ( codigo_suscripcion );

CREATE TABLE tbl_tipo_autenticacion (
    codigo_tipo_autenticacion   INTEGER NOT NULL,
    tipo_autenticacion          VARCHAR2(25)
);

ALTER TABLE tbl_tipo_autenticacion ADD CONSTRAINT tbl_tipo_autenticacion_pk PRIMARY KEY ( codigo_tipo_autenticacion );

CREATE TABLE tbl_tipo_historial (
    codigo_tipo_historial        INTEGER NOT NULL,
    descripcion_tipo_historial   VARCHAR2(50)
);

ALTER TABLE tbl_tipo_historial ADD CONSTRAINT tbl_tipo_historial_pk PRIMARY KEY ( codigo_tipo_historial );

CREATE TABLE tbl_tipo_like (
    codigo_tipo_like   INTEGER NOT NULL,
    tipo_like          VARCHAR2(25)
);

ALTER TABLE tbl_tipo_like ADD CONSTRAINT tbl_tipo_like_pk PRIMARY KEY ( codigo_tipo_like );

CREATE TABLE tbl_tipo_perfil (
    codigo_tipo_perfil   INTEGER NOT NULL,
    tipo_perfil          VARCHAR2(50)
);

ALTER TABLE tbl_tipo_perfil ADD CONSTRAINT tbl_tipo_perfil_pk PRIMARY KEY ( codigo_tipo_perfil );

CREATE TABLE tbl_tipo_publicacion (
    codigo_tipo_publicacion   INTEGER NOT NULL,
    descripcion_tipo_publi    VARCHAR2(25)
);

ALTER TABLE tbl_tipo_publicacion ADD CONSTRAINT tbl_tipo_publicacion_pkv1 PRIMARY KEY ( codigo_tipo_publicacion );

CREATE TABLE tbl_usuarios (
    codigo_usuario              INTEGER NOT NULL,
    codigo_genero               INTEGER NOT NULL,
    codigo_tipo_perfil          INTEGER NOT NULL,
    codigo_lugar                INTEGER,
    codigo_act_notificaciones   INTEGER NOT NULL,
    codigo_estado_act           INTEGER NOT NULL,
    codigo_compartir_historia   INTEGER NOT NULL,
    codigo_inhabilitar_cuenta   INTEGER,
    codigo_agregar_foto         INTEGER,
    codigo_canal                INTEGER,
    correo_usuario              VARCHAR2(100) NOT NULL,
    nombre_perfil_usuario       VARCHAR2(50) NOT NULL,
    password                    VARCHAR2(50) NOT NULL,
    fecha_registro              DATE NOT NULL,
    nombre_usuario              VARCHAR2(50),
    apellido_usuario            VARCHAR2(50),
    fecha_nacimiento            DATE,
    numero_telefono             VARCHAR2(50),
    sitio_web                   BLOB,
    biografia                   VARCHAR2(250),
    foto_perfil                 CLOB
);

ALTER TABLE tbl_usuarios ADD CONSTRAINT tbl_usuario_pk PRIMARY KEY ( codigo_usuario );

ALTER TABLE tbl_usuarios ADD CONSTRAINT tbl_usuario__un UNIQUE ( nombre_perfil_usuario,
                                                                 correo_usuario );

ALTER TABLE tbl_accesos
    ADD CONSTRAINT tbl_accesos_tbl_usua_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_agregar_fotos_filtro
    ADD CONSTRAINT tbl_agre_fotos_tbl_filt_fk FOREIGN KEY ( codigo_filtro )
        REFERENCES tbl_filtros ( codigo_filtro );

ALTER TABLE tbl_agregar_fotos_filtro
    ADD CONSTRAINT tbl_agre_fotos_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_autenticacion
    ADD CONSTRAINT tbl_auten_tbl_tipo_auten_fk FOREIGN KEY ( codigo_tipo_autenticacion )
        REFERENCES tbl_tipo_autenticacion ( codigo_tipo_autenticacion );

ALTER TABLE tbl_autenticacion
    ADD CONSTRAINT tbl_autenticacion_tbl_usua_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_bloqueo_usuarios
    ADD CONSTRAINT tbl_blo_usus_tbl_usu_fk FOREIGN KEY ( codigo_usuario_bloqueado )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_bloqueo_usuarios
    ADD CONSTRAINT tbl_bloq_usu_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_comentario
    ADD CONSTRAINT tbl_comen_tbl_comen_fk FOREIGN KEY ( codigo_comentario_superior )
        REFERENCES tbl_comentario ( codigo_comentario );

ALTER TABLE tbl_comentario
    ADD CONSTRAINT tbl_coment_tbl_publ_fk FOREIGN KEY ( codigo_publicacion )
        REFERENCES tbl_publicaciones ( codigo_publicacion );

ALTER TABLE tbl_comentario
    ADD CONSTRAINT tbl_coment_tbl_usua_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_etiquetas
    ADD CONSTRAINT tbl_etiq_tbl_publi_fk FOREIGN KEY ( codigo_publicacion )
        REFERENCES tbl_publicaciones ( codigo_publicacion );

ALTER TABLE tbl_etiquetas
    ADD CONSTRAINT tbl_etiquetas_tbl_usu_fk FOREIGN KEY ( codigo_usuario_etiquetado )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_favoritos
    ADD CONSTRAINT tbl_favo_tbl_publi_fk FOREIGN KEY ( codigo_publicacion )
        REFERENCES tbl_publicaciones ( codigo_publicacion );

ALTER TABLE tbl_historiales
    ADD CONSTRAINT tbl_hist_tbl_tipo_hist_fk FOREIGN KEY ( codigo_tipo_historial )
        REFERENCES tbl_tipo_historial ( codigo_tipo_historial );

ALTER TABLE tbl_historiales
    ADD CONSTRAINT tbl_hist_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_igtv
    ADD CONSTRAINT tbl_igtv_tbl_canal_videos_fk FOREIGN KEY ( codigo_canal )
        REFERENCES tbl_canal_videos ( codigo_canal );

ALTER TABLE tbl_igtv
    ADD CONSTRAINT tbl_igtv_tbl_vista_previa_fk FOREIGN KEY ( codigo_vista_previa )
        REFERENCES tbl_compartir_vista_previa ( codigo_vista_previa );

ALTER TABLE tbl_int_emoji
    ADD CONSTRAINT tbl_int_emji_tbl_com_fk FOREIGN KEY ( codigo_comentario )
        REFERENCES tbl_comentario ( codigo_comentario );

ALTER TABLE tbl_int_emoji
    ADD CONSTRAINT tbl_int_emji_tbl_msj_fk FOREIGN KEY ( codigo_mensaje )
        REFERENCES tbl_mensajes ( codigo_mensaje );

ALTER TABLE tbl_int_emoji
    ADD CONSTRAINT tbl_int_emoji_tbl_emj_fk FOREIGN KEY ( codigo_emoji )
        REFERENCES tbl_emojis ( codigo_emoji );

ALTER TABLE tbl_likes
    ADD CONSTRAINT tbl_lik_tbl_publ_fk FOREIGN KEY ( codigo_publicacion )
        REFERENCES tbl_publicaciones ( codigo_publicacion );

ALTER TABLE tbl_likes
    ADD CONSTRAINT tbl_like_tbl_com_fk FOREIGN KEY ( codigo_comentario )
        REFERENCES tbl_comentario ( codigo_comentario );

ALTER TABLE tbl_likes
    ADD CONSTRAINT tbl_likes_tbl_tipo_like_fk FOREIGN KEY ( codigo_tipo_like )
        REFERENCES tbl_tipo_like ( codigo_tipo_like );

ALTER TABLE tbl_likes
    ADD CONSTRAINT tbl_likes_tbl_usuario_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_lugares
    ADD CONSTRAINT tbl_lugares_tbl_lugares_fk FOREIGN KEY ( codigo_lugar_padre )
        REFERENCES tbl_lugares ( codigo_lugar );

ALTER TABLE tbl_mensajes
    ADD CONSTRAINT tbl_msj_tbl_emi_fk FOREIGN KEY ( codigo_emisor )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_mensajes
    ADD CONSTRAINT tbl_msj_tbl_recep_fk FOREIGN KEY ( codigo_receptor )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_mensajes
    ADD CONSTRAINT tbl_msj_tbl_tipo_like_fk FOREIGN KEY ( codigo_tipo_like )
        REFERENCES tbl_tipo_like ( codigo_tipo_like );

ALTER TABLE tbl_palabras_filtro
    ADD CONSTRAINT tbl_pal_fil_tbl_fil_com_fk FOREIGN KEY ( codigo_palabra )
        REFERENCES tbl_filtro_comentarios ( codigo_palabra );

ALTER TABLE tbl_palabras_filtro
    ADD CONSTRAINT tbl_pal_filtro_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_publicaciones_guardadas
    ADD CONSTRAINT tbl_pub_guar_tbl_publ_fk FOREIGN KEY ( codigo_publicacion )
        REFERENCES tbl_publicaciones ( codigo_publicacion );

ALTER TABLE tbl_publicaciones_guardadas
    ADD CONSTRAINT tbl_publi_guar_tbl_usu_fk FOREIGN KEY ( codigo_usuario_guarda )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_publicaciones
    ADD CONSTRAINT tbl_publi_tbl_cat_publi_fk FOREIGN KEY ( codigo_categoria )
        REFERENCES tbl_categorias_publicacion ( codigo_categoria );

ALTER TABLE tbl_publicaciones
    ADD CONSTRAINT tbl_publi_tbl_ext_publi_fk FOREIGN KEY ( codigo_extension_publicacion )
        REFERENCES tbl_extension_publicacion ( codigo_extension_publicacion );

ALTER TABLE tbl_publicaciones
    ADD CONSTRAINT tbl_publi_tbl_tipo_publi_fk FOREIGN KEY ( codigo_tipo_publicacion )
        REFERENCES tbl_tipo_publicacion ( codigo_tipo_publicacion );

ALTER TABLE tbl_publicaciones
    ADD CONSTRAINT tbl_public_tbl_usua_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_seguidos
    ADD CONSTRAINT tbl_segui_tbl_solic_segui_fk FOREIGN KEY ( codigo_solicitud )
        REFERENCES tbl_solicitud_seguidores ( codigo_solicitud );

ALTER TABLE tbl_seguidos
    ADD CONSTRAINT tbl_segui_tbl_usuario_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_seguidos
    ADD CONSTRAINT tbl_segui_usuario_fk FOREIGN KEY ( codigo_seguidor )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_susc_usu
    ADD CONSTRAINT tbl_sus_usu_tbl_susc_fk FOREIGN KEY ( codigo_suscripcion )
        REFERENCES tbl_suscripciones ( codigo_suscripcion );

ALTER TABLE tbl_susc_usu
    ADD CONSTRAINT tbl_sus_usu_tbl_usu_fk FOREIGN KEY ( codigo_usuario )
        REFERENCES tbl_usuarios ( codigo_usuario );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usu_tbl_act_not_fk FOREIGN KEY ( codigo_act_notificaciones )
        REFERENCES tbl_activar_notificaciones ( codigo_activacion );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usu_tbl_agregar_fotos_fk FOREIGN KEY ( codigo_agregar_foto )
        REFERENCES tbl_agregar_fotos_filtro ( codigo_agregar_foto );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usu_tbl_canal_videos_fk FOREIGN KEY ( codigo_canal )
        REFERENCES tbl_canal_videos ( codigo_canal );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usu_tbl_comp_hist_fk FOREIGN KEY ( codigo_compartir_historia )
        REFERENCES tbl_compartir_historias ( codigo_compartir_historia );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usu_tbl_est_act_fk FOREIGN KEY ( codigo_estado_act )
        REFERENCES tbl_estado_actividad ( codigo_estado_act );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usu_tbl_inhab_fk FOREIGN KEY ( codigo_inhabilitar_cuenta )
        REFERENCES tbl_inhabilitar_cuenta ( codigo_inhabilitar_cuenta );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usuario_tbl_genero_fk FOREIGN KEY ( codigo_genero )
        REFERENCES tbl_genero ( codigo_genero );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usuario_tbl_lugares_fk FOREIGN KEY ( codigo_lugar )
        REFERENCES tbl_lugares ( codigo_lugar );

ALTER TABLE tbl_usuarios
    ADD CONSTRAINT tbl_usuario_tbl_tipo_perfil_fk FOREIGN KEY ( codigo_tipo_perfil )
        REFERENCES tbl_tipo_perfil ( codigo_tipo_perfil );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            38
-- CREATE INDEX                             0
-- ALTER TABLE                             84
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
