--CREACION DE SECUENCIAS
CREATE SEQUENCE USUARIO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CODIGO_ACCESO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CODIGO_CANAL INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CODIGO_CATEGORIA INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CODIGO_LUGAR INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CODIGO_PUBLICACION INCREMENT BY 1 START WITH 1;